import { WorkflowRun } from "@/components/Runs/runcard";

export const mockRuns: WorkflowRun[] = [
    {
        id: "cmcc9q1650002s520vp2r73kn",
        status: "COMPLETED",
        userQuery: "Find nice two bedroom apartments for me and my family in downtown Toronto",
        queryType: "accommodation",
        location: "Toronto, ON",
        guestCount: 4,
        credits: 7,
        startedAt: new Date(Date.now() - 33 * 60 * 1000).toISOString(),
        completedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        results: 12,
    },
    {
        id: "cmcc9q1650002s520vp2r73ko",
        status: "FAILED",
        userQuery: "Book flights from NYC to Paris for next week",
        queryType: "transport",
        location: "New York, NY",
        guestCount: 2,
        credits: 5,
        startedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        error: "No available flights found for the specified dates",
    },
    {
        id: "cmcc9q1650002s520vp2r73kp",
        status: "RUNNING",
        userQuery: "Find family-friendly restaurants near Times Square",
        queryType: "restaurant",
        location: "New York, NY",
        guestCount: 3,
        credits: 3,
        startedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    },
    {
        id: "cmcc9q1650002s520vp2r73kq",
        status: "COMPLETED",
        userQuery: "Suggest outdoor activities in Vancouver for weekend",
        queryType: "activity",
        location: "Vancouver, BC",
        guestCount: 2,
        credits: 4,
        startedAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
        completedAt: new Date(Date.now() - 115 * 60 * 1000).toISOString(),
        results: 8,
    },
  ];